# Generated by Django 2.2.13 on 2021-04-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='authors', to='dojoApp.Book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_books', to='loginApp.User'),
        ),
    ]
